CREATE TABLE reviews (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  review_id UUID NOT NULL,
  book_id TEXT NOT NULL,
  title TEXT,
  contents TEXT,
  help_count INTEGER NOT NULL,
  user_id INTEGER REFERENCES users(id)
);



